### ISSUE TITLE
keybd.type_string not support Chinese.

### ISSUE THREAD

**Issue by leechaowen** [ChiHangChen/KeyboardSimulator#14]
it's pity keybd.type_string  not support Chinese.Could you help improve it ?

> keybd.type_string("我爱你")
Error in keybd.type_string("我爱你") : 
  The 'button' value '我' is not supported. Available keys are : a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 1 2 3 4 5 6 7 8 9 0 num0 num1 num2 num3 num4 num5 num6 num7 num8 num9 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 backspace tab enter shift ctrl alt capslock esc pageup pagedown end home left up right down insert   del numlock win ` ~ ! @ # $ % ^ & * ( ) - _ + = [ { ] } \ | ; : ' " , < . > / ?

**Comment by ChiHangChen** [comment]
KeyboardSimulator is designed for press a single key, so you must decomposition the word "我爱你" into several key combination, and then implement to KeyboardSimulator supported key
