### ISSUE TITLE
Screensaver/screen lock prevention

### ISSUE THREAD

**Issue by larsedler** [ChiHangChen/KeyboardSimulator#15]
I noticed that the package's function `mouse.move()` will not prevent the screensaver or the screen lock from becoming active. Is it a bug of feature? For monitoring reasons it would be great to have the option of prevention. Thanks!

**Comment by jeffkeller87** [comment]
My understanding is that this is a limitation of the Windows API function being used to control the mouse ([`SetCursorPos`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcursorpos)). [It sounds like](https://stackoverflow.com/questions/463813/programmatically-prevent-windows-screensaver-from-starting) the newer and more generic Windows interface for controlling inputs, [`sendInput`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) will prevent the computer from sleeping/locking.

**Comment by larsedler** [comment]
Thanks, @jeffkeller87, for the clarification.
