### ISSUE TITLE
Does not work with Windows Task Scheduler when not logged in

### ISSUE THREAD

**Issue by yb2125** [ChiHangChen/KeyboardSimulator#21]
First, thank you for developing this package! It works beautifully when I am using my computer (even if R is not in the foreground). However, the problem I am trying to solve involves running the script every night on a server. I set up a scheduled task using Windows Task Scheduler, but the same script does not work on the server. Any suggestion?

**Comment by yb2125** [comment]
If it helps, I added lines to track the actual cursor location at each step. Instead of moving to the designated location, the cursor remained at 48, 0.

**Comment by ChiHangChen** [comment]
Hi, could you help to try to run Windows Task Scheduler as Administrator and see if the problem remains?
