### ISSUE TITLE
Problem with slash in keybd.type_string

### ISSUE THREAD

**Issue by roroba** [ChiHangChen/KeyboardSimulator#23]
I am having problems to get this address with 

keybd.type_string(https://twitter.com/me_duele_mexico/status/1501776156504244226/photo/1)

I only get this result:

https¨}}https://twitter.com}me_duele_mexico}status}1501776156504244226}photo}1

**Comment by jeffkeller87** [comment]
You need to quote the string. This gives me the expected results:

```r
keybd.type_string("https://twitter.com/me_duele_mexico/status/1501776156504244226/photo/1")
```

**Comment by roroba** [comment]
Yes I agree. Sorry for my bad example, here I make some better example of my problem:

Previously I have a txt file with name: "imagenes.txt" with this web address:
https://twitter.com/TreceBarras13/status/1501939685152608259/photo/1

    ima=read.table("imagenes.txt", sep="\t")

    #Here I check that web adress is right
    ima
    https://twitter.com/TreceBarras13/status/1501939685152608259/photo/1
    
    #Everything its ok

    #Here I get the problem when Keyboard Simulator type the web address
    keybd.type_string(ima)

#All the slash are replaced by "}" sign: 

 https¨}}twitter.com}TreceBarras13}status}1501939685152608259}photo}1

**Comment by ChiHangChen** [comment]
The above code works perfect on me, may I ask what kind of keyboard you are using?
According to [Microsoft doc](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes). the virtual code might be vary by keyboard
![image](https://user-images.githubusercontent.com/22412708/157820181-e8e30163-c0cf-4a40-ad16-d29a3441947e.png)

**Comment by roroba** [comment]
Hi

Thanks for you reply!

Your comments help me to fix my problem. I had a spanish, latinamerican
keyboard.

Now my command work great
Thanks

Saludos.
Rodrigo Badilla.
+56 962202469
