### ISSUE TITLE
Keys for command line results in "Error, attempt to apply non-function"

### ISSUE THREAD

**Issue by charleswidnall** [ChiHangChen/KeyboardSimulator#25]
I would like to know if it is possible to use _keyboardSimulator_ to enter a command at the command line. From the description of the package, it sounds as it should be able to do it, but I'm stuck with a single command that doesn't want to budge, and stops the execution with an error ("attempt to apply non-function").

To provide some context, I need to do a screenshot of a Viewer pane, for a few files, one at a time, and cannot be hitting 'Enter' continuously. There is a nice procedure for a _single_ screenshot, using _websocket,_ at 
```
   https://stackoverflow.com/questions/50946083/how-to-save-viewer-pane-as-image-through-command-line
```
(middle of the page in the url, "The Code", reproduced below). If I run those lines in one go, the process reports, "Error, attempt to apply non-function", at the line
```
   websocket$send("go") # send any message
```
However, the process works well if I execute in block from the start until the previous line, select the offending line [websocket$send("go")], and press either (a) 'Enter' or (b) "Run" at the top. In these cases it produces the png file perfectly. 

I tried to replace 'websocket$send("go")' with
```
    keybd.type_string('websocket$send(\"go\")'); keybd.press("Enter")
```
or 
```
    keybd.type_string('websocket$send(\"go\")'); mouse.click(); mouse.release()
```

but, in these cases, although I don't receive any error, the websocket is not called, pdf continues to be NULL, and no png file is produced (showing another error when it tries to download it).

I'm sure I'm writing something wrong to execute the command line. I'd also like to produce a shorter code but I'm afraid it may not reproduce the exact chain of events (Viewer -> websocket -> png -> download), although I think the issue is with formatting that single line of code correctly.

Can you provide some guidance?

Thank you so much ...

 
```
# From https://stackoverflow.com/questions/50946083/how-to-save-viewer-pane-as-image-through-command-line
# Updated two deprecated commands to start and stop the server

library(httpuv)

# Initialize variables
png <- NULL
websocket <- NULL

# Download Javascript libraries
polyfill_promise <- readLines('https://cdn.jsdelivr.net/npm/es6-promise/dist/es6-promise.auto.min.js')
html2canvas <- readLines('https://html2canvas.hertzen.com/dist/html2canvas.min.js')

# Configure the httpuv server
app <- list(
  call = function(req) {
    list(
      status  = 200L,
      headers = list( 'Content-Type' = 'text/html' ),
      body = paste0(collapse = "\r\n",
                    c("<!DOCTYPE html>",
                      "<html>", 
                      "<head>",
                      # polyfill the RStudio viewer to support JavaScript promises
                        '<script type="text/javascript">', polyfill_promise, "</script>",
                      # use html2canvas library
                        '<script type="text/javascript">', html2canvas, "</script>",
                      "</head>",

                      "<body>", html_body, "</body>",
                      '<script type="text/javascript">',
                      # Configure the client-side websocket connection:
                        'var ws = new WebSocket("ws://" + location.host);',
                      # When a websocket message is received:
                        "ws.onmessage = function(event) {",
                      # Take a screenshot of the HTML body element
                        "  html2canvas(document.body).then(function(canvas) {",
                      # Transform it to png
                        "    var dataURL = canvas.toDataURL();",
                      # Send it back to the server
                        "    ws.send(dataURL);",
                        "  });",
                        "};",
                      "</script>",
                      "</html>"
                    )
      )
    )
  },
  # Configure the server-side websocket connection
  onWSOpen = function(ws) {
    # because we need to send websocket message from the R command line:
      websocket <<- ws
    # when a websocket message is received from the client
      ws$onMessage(function(binary, message) {
        png <<- message
    })
  }
)

# From the original question:
html_body <- c(
  '<h1> Content</h1>', 
  '<h2> Content</h2>', 
  'lorem ipsum...'
)

# Start the server:
server <- startServer("0.0.0.0", 9454, app) # deprecated -> startDaemonizedServer("0.0.0.0", 9454, app)

# Open the RStudio viewer:
  rstudioapi::viewer("http://localhost:9454")
# Wait to see the result...

# Send a websocket message from the command line: 
  websocket$send("go") # send any message    # <=========== How to modify this line with keyboardSimulator?

# Write the png image to disk:
writeBin(
  RCurl::base64Decode( gsub("data:image/png;base64,", "", png), "raw" ), 
  "screenshot.png"
)

# Close the websocket connection
  websocket$close()

# Stop the server
  stopServer(server) # deprecated -> stopDaemonizedServer(server)
```

**Comment by jeffkeller87** [comment]
How are you executing the big block of code? If you are doing something like:

```bash
Rscript my_script.R
```

Then using {KeyboardSimulator} inside of `my_script.R` isn't going to do what you want.

If you are running this code interactively, I think using {KeyboardSimulator} is _possible_ but probably not the best solution. Running interactive code to simulate interactive user inputs gets hairy very quickly. I think you'd be better off looping over files.

An even better solution I think would be to use the [{webshot}](https://wch.github.io/webshot/articles/intro.html) package to open the HTML files in a headless browser and take the screenshots that way.

**Comment by ChiHangChen** [comment]
I think the problem

> run all lines in one go

not working but

> run websocket$send("go") by block

worked is because:
> Your `startDaemonizedServer` is not setup yet, that is to say, the function `onWSOpen` in `app` wont be executed until your program finished

so your `websocket` is `NULL` until the program end, that is why you get `Error, attempt to apply non-function` because you keep calling `send` method from a NULL (`websocket`) object.

I think using `KeyboardSimulator` to solve this problem is not the best solution, try with other ways or packages to get your HTML output.

**Comment by charleswidnall** [comment]
Thanks. I'll try using another procedure.
