### ISSUE TITLE
R 4.3.X not working?

### ISSUE THREAD

**Issue by taustring** [ChiHangChen/KeyboardSimulator#28]
I am getting this error when trying to use mouse.click in R 4.3.0 and 4.3.1, but everything works fine in 4.2.3

`KeyboardSimulator::mouse.click()`
`Error in .Call("_KeyboardSimulator_mouse_left_click", PACKAGE = "KeyboardSimulator") : 
  "_KeyboardSimulator_mouse_left_click" not available for .Call() for package "KeyboardSimulator"`

**Comment by evanjpatton** [comment]
I came here to make the same comment. Except it was working for me in version 4.3.0. Installed 4.3.1 yesterday and am now getting the same error.

**Comment by supersouce** [comment]
I also getting this error when using this R package 2.6.1 by R 4.3.1
I don't know how to create R package, so I am unable to identify the specific reason for this error. But based on some information on CSDN, I speculate that there were some issues during the R package production process.After comparing the NAMESPACE information in the source files of versions 2.6.1 and 2.6.0, it was found that 2.6.1 is indeed missing two lines of code compared to 2.6.0. This code also conforms to the solution found in CSDN to address such error messages.
Hope my suggestions can help the producers, Possible solutions are as follows[https://blog.csdn.net/weixin_41929524/article/details/101517979](url)

**Comment by jeffkeller87** [comment]
I no longer have a Windows machine to work on this package, but hopefully @ChiHangChen can chime in.

**Comment by ChiHangChen** [comment]
OK, Let me try to rebuild package with R4.3.1 and get back to you guys ASAP

**Comment by ChiHangChen** [comment]
I think this error probably happens at 2.6.1 changed due to https://github.com/r-lib/roxygen2/issues/1491...
But currently I can't not find a working way in my test

**Comment by ChiHangChen** [comment]
I think this bugs comes from roxygen updated and the following line under namespace are missing

```
import(Rcpp)
useDynLib(KeyboardSimulator)
```

I already make a fix in this commit(https://github.com/ChiHangChen/KeyboardSimulator/commit/44fff2d7276e29b47ffb392b9a5930b281e72584)

After few hours the latest binary pushed to CRAN, please update your package version to 2.6.2 and it should work again.

Apologize again

**Comment by jeffkeller87** [comment]
`packrat` has the development dependencies pinned to `roxygen2` 6.1.1 so I'm not sure how a bug related to 7.0.0+ could have appeared?

https://github.com/ChiHangChen/KeyboardSimulator/blob/master/packrat/packrat.lock#L191

**Comment by Combogic** [comment]
Yeah... thanks for point out that jeff.
I think when I built source binary in `Rstudio` I didn't use the version setting in `packrat` correctly...will be more careful when publish new version in the futures

**Comment by ChiHangChen** [comment]
Yeah... thanks for point that out Jeff.
I think when I built source binary in `Rstudio` I didn't use the version setting in `packrat` correctly...will be more careful when publish new version in the futures
