### ISSUE TITLE
any plan to mouse move with time?

### ISSUE THREAD

**Issue by mrchypark** [ChiHangChen/KeyboardSimulator#4]
I want to add time to the mouse.move() function to make the pointer move slowly. Are there any such improvements planned?

Thank you for making the package.

**Comment by jeffkeller87** [comment]
@ChiHangChen this should be doable with some basic interpolation between the current mouse position and the target position, and some delayed calls to the `MouseMove` function.

**Comment by ChiHangChen** [comment]
OK, I'll try to add an argument in `mouse.move()` function to achieve that, may call it `duration` ?

**Comment by ChiHangChen** [comment]
@mrchypark I have added 2 new argument in `mouse.move` function called `duration` and `step_ratio`, please give it a try and report any problems, million thanks!

**Comment by mrchypark** [comment]
@ChiHangChen I'll try! many thanks!
