### ISSUE TITLE
Can't install package for some reason

### ISSUE THREAD

**Issue by kschubert417** [ChiHangChen/KeyboardSimulator#6]
When I try to install the package I get an error saying that it is not available for R version 3.3.3

See my code below:
> install.packages("KeyboardSimulator")
Installing package into ‘C:/Users/SchubertK/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘KeyboardSimulator’ is not available (for R version 3.3.3)

**Comment by ChiHangChen** [comment]
Sorry for the late reply, could you try to install package through github?
```
if (!require("devtools")) install.packages("devtools")
devtools::install_github("ChiHangChen/KeyboardSimulator")
```

**Comment by jeffkeller87** [comment]
`KeyboardSimulator` was not on CRAN when R 3.3.3 was the current version, so CRAN does not have any pre-compiled binaries available for that version. You may install the development version as @ChiHangChen mentioned above, or you can still install the package from CRAN, but install it from source instead:

```
install.packages("KeyboardSimulator", type = "source")
```
