### ISSUE TITLE
How to use KeyboardSimulator in Laptop with Screen closed

### ISSUE THREAD

**Issue by GuilleFB** [ChiHangChen/KeyboardSimulator#9]
I am using KeyboardSimulator to do a task but when I close the Laptopt screen It doesn't work. I have implemented a Loop and It run in R because I receiv the alarm when It finish but the mouse movement and the key press don't work. Is it possible to use if I close my laptop screen? I have proved with the screen saver and it work but not if I close the screen laptop.

**Comment by jeffkeller87** [comment]
This likely depends on the behaviour of the laptop when the lid is closed. If closing the lid puts the computer into hibernation, logs the user out, or locks the screen, then the simulated mouse and keyboard actions will not behave as expected.

You can try [adjusting your Windows power option settings](https://www.howtogeek.com/412876/how-to-keep-your-laptop-on-with-the-lid-closed-on-windows-10/) to see if you can get the behaviour you're after.
